#!/bin/bash
grep -c "bin" /etc/passwd#!/bin/bash
grep -c "bin" /etc/passwd#!/bin/bash
grep -c "bin" /etc/passwd#!/bin/bash
grep -c "bin" /etc/passwd#!/bin/bash
grep -c "bin" /etc/passwd#!/bin/bash
grep -c "bin" /etc/passwd#!/bin/bash
grep -c "bin" /etc/passwd#!/bin/bash
grep -c "bin" /etc/passwd
